# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='favs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field=300, max_length=200, null=True, upload_to='img', width_field=300),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
