# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0002_auto_20170902_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field=300, max_length=200, null=True, upload_to='img', verbose_name='图片', width_field=300),
        ),
    ]
