# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0003_auto_20170903_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='标题'),
        ),
    ]
