# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0006_auto_20170903_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('全部', 'All'), ('知识', 'Tech'), ('生活', 'Life')], max_length=5, null=True),
        ),
    ]
