# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0011_auto_20170907_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='createdOn',
        ),
    ]
