# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0013_auto_20170911_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(blank=True, default='http://semantic-ui.com/images/avatar/small/matt.jpg', max_length=500, null=True),
        ),
    ]
