# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0019_comment_best_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(null=True, upload_to='cover_image'),
        ),
    ]
