# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getExercise', '0022_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_tickets', to='getExercise.UserProfile'),
        ),
    ]
